language: rust

sudo: required
cache:
  directories:
    - /home/travis/.cargo

before_cache:
  - RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin
  - rm -rf /home/travis/.cargo/registry
include_base: &BASE
  addons:
    apt:
      sources: &BASE_SOURCES
        - ubuntu-toolchain-r-test
      packages: &BASE_PACKAGES
        - libelf-dev
        - lib32z1-dev
        - libedit-dev
        - libdw-dev
        - binutils-dev
        - libiberty-dev
        - libssl-dev
  before_install:
    - export LLVM_VERSION_DASH=${LLVM_VERSION/./-}
    - export LLVM_VERSION_SHORT=${LLVM_VERSION/./}
    - export PATH=/usr/lib/llvm-${LLVM_VERSION}/bin/:$HOME/.local/bin:$PATH
    - export LLVM_PATH=/usr/share/llvm-${LLVM_VERSION}/cmake/
    - sed -i -e 's/llvm-sys = ".*"/llvm-sys = "'${LLVM_VERSION_SHORT}'"/' Cargo.toml
  script:
    - cargo build --no-default-features --features "llvm${LLVM_VERSION_DASH}" --color=always
    - cargo test --no-default-features --features "llvm${LLVM_VERSION_DASH}" --verbose --color=always

matrix:
  fast_finish: true
  include:
    - env:
        - LLVM_VERSION="3.6"
      <<: *BASE
      addons:
        apt:
          sources:
            - *BASE_SOURCES
            - llvm-toolchain-precise-3.6
          packages:
            - *BASE_PACKAGES
            - llvm-3.6-dev
      rust: nightly-2019-01-15
    - env:
        - LLVM_VERSION="3.7"
      <<: *BASE
      addons:
        apt:
          sources:
            - *BASE_SOURCES
            - llvm-toolchain-precise-3.7
          packages:
            - *BASE_PACKAGES
            - llvm-3.7-dev
      rust: nightly-2019-01-15
    - env:
        - LLVM_VERSION="3.8"
      <<: *BASE
      addons:
        apt:
          sources:
            - *BASE_SOURCES
            - llvm-toolchain-precise-3.8
          packages:
            - *BASE_PACKAGES
            - llvm-3.8-dev
      rust: nightly-2019-01-15
    # 3.9 seems to have a linking issue :/
    # - env:
    #     - LLVM_VERSION="3.9"
    #   <<: *BASE
    #   addons:
    #     apt:
    #       sources:
    #         - *BASE_SOURCES
    #         - llvm-toolchain-trusty-3.9
    #       packages:
    #         - *BASE_PACKAGES
    #         - llvm-3.9-dev
    - env:
        - LLVM_VERSION="4.0"
      <<: *BASE
      addons:
        apt:
          sources:
            - *BASE_SOURCES
            - llvm-toolchain-trusty-4.0
          packages:
            - *BASE_PACKAGES
            - llvm-4.0-dev
      rust: nightly-2019-01-15
    - env:
        - LLVM_VERSION="5.0"
      <<: *BASE
      addons:
        apt:
          sources:
            - *BASE_SOURCES
            - llvm-toolchain-trusty-5.0
          packages:
            - *BASE_PACKAGES
            - llvm-5.0-dev
      rust: nightly-2019-01-15
    - env:
        - LLVM_VERSION="6.0"
      <<: *BASE
      addons:
        apt:
          sources:
            - *BASE_SOURCES
            - llvm-toolchain-trusty-6.0
          packages:
            - *BASE_PACKAGES
            - llvm-6.0-dev
      rust: nightly-2019-01-15
    - env:
        - LLVM_VERSION="7.0"
      <<: *BASE
      addons:
        apt:
          sources:
            - *BASE_SOURCES
            - llvm-toolchain-trusty-7
          packages:
            - *BASE_PACKAGES
            - llvm-7-dev
      rust: nightly-2019-01-15
    - deploy: # Documentation build; Only latest supported LLVM version for now
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
        keep-history: false
        local-dir: target/doc/
        on:
          branch: master
      before_install:
        - export PATH=/usr/lib/llvm-7/bin/:$HOME/.local/bin:$PATH
        - export LLVM_PATH=/usr/share/llvm-7/cmake/
      script:
        - cargo doc --no-default-features --features llvm7-0 --color=always
        - echo '<meta http-equiv="refresh" content="1; url=inkwell/index.html">' > target/doc/index.html
      rust: nightly
      name: "GitHub IO Documentation Deployment"
      addons:
        apt:
          sources:
            - *BASE_SOURCES
            # - llvm-toolchain-precise-3.6
            # - llvm-toolchain-precise-3.7
            # - llvm-toolchain-precise-3.8
            # - llvm-toolchain-trusty-3.9
            # - llvm-toolchain-trusty-4.0
            # - llvm-toolchain-trusty-5.0
            # - llvm-toolchain-trusty-6.0
            - llvm-toolchain-trusty-7
          packages:
            - *BASE_PACKAGES
            # - llvm-3.6-dev
            # - llvm-3.7-dev
            # - llvm-3.8-dev
            # - llvm-3.9-dev
            # - llvm-4.0-dev
            # - llvm-5.0-dev
            # - llvm-6.0-dev
            - llvm-7-dev

env:
  global:
    - RUSTFLAGS="-C link-dead-code -C target-cpu=native -l ffi"

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == nightly-2019-01-15 ]]; then
    cargo tarpaulin --features "llvm${LLVM_VERSION_DASH}" --ignore-tests --out Xml
    bash <(curl -s https://codecov.io/bash)
  fi

notifications:
  email: false
