language: rust

sudo: false

rust:
  - stable
  - beta
  - nightly

# Shared Packages
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libelf-dev
      - lib32z1-dev
      - libedit-dev
      - libdw-dev
      - binutils-dev
      - libiberty-dev

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
  include:
    # LLVM 3.6
    - addons:
        apt:
          sources:
            - llvm-toolchain-precise-3.6
          packages:
            - llvm-3.6-dev
      before_install:
        - export PATH=/usr/lib/llvm-3.6/bin/:$HOME/.local/bin:$PATH
    # LLVM 3.7
    - addons:
        apt:
          sources:
            - llvm-toolchain-precise-3.7
          packages:
            - llvm-3.7-dev
      before_install:
        - export PATH=/usr/lib/llvm-3.7/bin/:$HOME/.local/bin:$PATH
env:
  global:
    - RUSTFLAGS="-C link-dead-code target-cpu=native"

after_success: |
  wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz &&
  tar xzf master.tar.gz &&
  cd kcov-master &&
  mkdir build &&
  cd build &&
  cmake .. &&
  make &&
  make install DESTDIR=../../kcov-build &&
  cd ../.. &&
  rm -rf kcov-master &&
  for file in $(find . -regextype posix-extended -regex "./target/debug/test(\w|-)+"); do mkdir -p "target/cov/$(basename $file)"; ./kcov-build/usr/local/bin/kcov --exclude-pattern=/.cargo,/usr/lib,tests --verify "target/cov/$(basename $file)" "$file"; done &&
  bash <(curl -s https://codecov.io/bash) &&
  echo "Uploaded code coverage"

notifications:
  email: false
