[package]
name = "inkwell"
version = "0.1.0"
authors = ["Daniel Kolsoi <thadan64@gmail.com>"]
description = "Inkwell aims to help you pen your own programming languages by safely wrapping llvm-sys."
repository = "https://github.com/TheDan64/inkwell"
readme = "README.md"
changelog = "CHANGELOG.md"
keywords = ["llvm", "safe", "wrapper"]
license = "Apache-2.0"
categories = ["development-tools::ffi"]

[features]
default = ["llvm6-0"]
llvm3-6 = []
llvm3-7 = []
llvm3-8 = []
llvm3-9 = []
llvm4-0 = []
llvm5-0 = []
llvm6-0 = []

[dependencies]
either = "1.5"
enum-methods = "0.0.8"
libc = "*"
llvm-sys = "60"

[badges]
travis-ci = { repository = "TheDan64/inkwell" }
codecov = { repository = "TheDan64/inkwell" }
