[package]
name = "inkwell"
version = "0.1.0"
authors = ["Daniel Kolsoi <thadan64@gmail.com>"]
description = "Inkwell aims to help you pen your own programming languages by safely wrapping llvm-sys."
repository = "https://github.com/TheDan64/inkwell"
readme = "README.md"
changelog = "CHANGELOG.md"
keywords = ["llvm", "safe", "wrapper"]
license = "Apache-2.0"
categories = ["development-tools::ffi"]

[features]
default = []
llvm3-6 = ["llvm3_6"]

[dependencies]
either = "1.1.0"
enum-methods = "0.0.7"
libc = "*"
llvm3_6 = { git = "https://github.com/serde-rs/serde", version="*", optional=true }

[[example]]
name = "kaleidoscope"
path = "examples/kaleidoscope/main.rs"

[badges]
travis-ci = { repository = "TheDan64/inkwell" }
codecov = { repository = "TheDan64/inkwell" }

[profile.dev]
codegen-units=32 # TODO: Remove when default in rust, cuts compile time ~50%
