[package]
name = "inkwell"
version = "0.1.0"
authors = ["Daniel Kolsoi <thadan64@gmail.com>"]
description = "Inkwell aims to help you pen your own programming languages by safely wrapping llvm-sys."
repository = "https://github.com/TheDan64/inkwell"
readme = "README.md"
keywords = ["llvm", "safe", "wrapper"]
license = "Apache-2.0"
categories = ["development-tools::ffi"]
edition = "2018"

[features]
default = ["target-all"]
# Please update internal_macros::FEATURE_VERSIONS when adding a new LLVM version
llvm3-6 = []
llvm3-7 = []
llvm3-8 = []
llvm3-9 = []
llvm4-0 = []
llvm5-0 = []
llvm6-0 = []
llvm7-0 = []
llvm8-0 = []
llvm9-0 = []
llvm10-0 = []
# Don't link aganist LLVM libraries. This is useful if another dependency is
# installing LLVM. See llvm-sys for more details.
no-llvm-linking = ["llvm-sys/no-llvm-linking"]
target-x86 = []
target-arm = []
target-mips = []
target-aarch64 = []
target-amdgpu = []
target-systemz = []
target-hexagon = []
target-nvptx = []
target-msp430 = []
target-xcore = []
target-powerpc = []
target-sparc = []
target-bpf = []
target-lanai = []
target-webassembly = []
target-all = [
    "target-x86",
    "target-arm",
    "target-mips",
    "target-aarch64",
    "target-amdgpu",
    "target-systemz",
    "target-hexagon",
    "target-nvptx",
    "target-msp430",
    "target-xcore",
    "target-powerpc",
    "target-sparc",
    "target-bpf",
    "target-lanai",
    "target-webassembly"
]
experimental = ["static-alloc"]

[dependencies]
either = "1.5"
inkwell_internals = { path = "./internal_macros", version = "0.1.0" }
libc = "0.2"
llvm-sys = "100.0.1"
once_cell = "1.2"
parking_lot = "0.10"
regex = "1"
static-alloc = { version = "0.2", optional = true }

[badges]
travis-ci = { repository = "TheDan64/inkwell" }
codecov = { repository = "TheDan64/inkwell" }
