[package]
name = "inkwell"
version = "0.1.0"
authors = ["Daniel Kolsoi <thadan64@gmail.com>"]
description = "Inkwell aims to help you pen your own programming languages by safely wrapping llvm-sys."
repository = "https://github.com/TheDan64/inkwell"
readme = "README.md"
keywords = ["llvm", "safe", "wrapper"]
license = "Apache-2.0"
categories = ["development-tools::ffi"]
edition = "2018"

[features]
default = []
llvm3-6 = []
llvm3-7 = []
llvm3-8 = []
llvm3-9 = []
llvm4-0 = []
llvm5-0 = []
llvm6-0 = []
llvm7-0 = []

[dependencies]
either = "1.5"
enum-methods = "0.0.8"
inkwell_internal_macros = { path = "./internal_macros", version = "0.1.0" }
libc = "0.2"
llvm-sys = "70.0"

[badges]
travis-ci = { repository = "TheDan64/inkwell" }
codecov = { repository = "TheDan64/inkwell" }
